title: ARIA Legal
description: Privacy Policy and Terms of Use for ARIA — in English and French
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - privacy-policy.md
  - terms-of-service.md
  - privacy-policy-fr.md
  - terms-of-service-fr.md
